# Generated by Django 5.2.8 on 2025-12-11 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True, verbose_name='Nome da Tag')),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_page', models.CharField(max_length=255, verbose_name='Título da Página')),
                ('description_page', models.TextField(verbose_name='Descrição da Página')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('image', models.ImageField(upload_to='blog_images/', verbose_name='Imagem')),
                ('cover_image', models.ImageField(upload_to='blog_cover_images/', verbose_name='Imagem de Capa')),
                ('summary_content', models.CharField(max_length=140, verbose_name='Resumo do Conteúdo')),
                ('content', models.TextField(verbose_name='Conteúdo')),
                ('slug', models.SlugField(max_length=60, unique=True, verbose_name='URL Amigável')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Editado em')),
                ('is_active', models.BooleanField(default=True, verbose_name='Está ativo')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('tags', models.ManyToManyField(blank=True, related_name='blog_posts', to='institucional.tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Postagem de Blog',
                'verbose_name_plural': 'Postagens de Blog',
                'ordering': ['-created_at'],
            },
        ),
    ]
